import './avatar/index'
import './badge/index'
import './code/index'
import './color/index'
import './drag/index'
import './form/index'
import './keyboard/index'
import './layer/index'
import './markd/index'
import './meditor/index'
import './neditor/index'
import './pager/index'
import './picker/date'
// import './picker/time'
import './slider/index'
// import './neditor/index'
// import './neditor/index'
// import './neditor/index'
